apiVersion: apps.openshift.io/v1 
kind: DeploymentConfig
metadata:
  name: sample1
spec:
  replicas: 2
  selector:
    deploymentconfig: sample1
  template:
    metadata:
      labels:
        deploymentconfig: sample1
    spec:
      containers:
      - image: adoptopenjdk:8-jdk-hotspot
        imagePullPolicy: Always
        name: sample1
        ports:
        - containerPort: 8090
        env:
        - name: USER
          value: "UserDefault"
        - name: PROFILES
          value: "DEV"
        - name: TIME_ZONE
          value: "Mexico City"